config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",registrations: "users/registrations"}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  root 'products#index'

  get '/search', to: 'products#search'
  get '/auto_search', to: 'products#auto_search'

  mount RuCaptcha::Engine => "/rucaptcha"

  namespace :admin do
    root 'home#dashboard'
    get '/root_manage', to: 'home#root_manage'

    resources :banners,only: [:create,:update,:destroy]

    resources :categories

    resources :products, except: [:show]

    resources :images, only: [:create] do
      delete 'del_image', on: :collection
    end

    resources :users, only: [:index, :edit, :update, :destroy] do
      post 'add', on: :collection
      delete 'remove', on: :member
    end

    resources :orders, only: [:index, :edit, :update, :destroy] do
      get "show_products", on: :member
      post 'deliver', on: :member
    end

    resources :coupons, only: [:index,:create]

    resources :awards, only: [:index,:create,:edit,:update,:destroy]
  end

  resources :products do
    get 'detail', on: :member
    resources :comments, only: [:index,:create, :destroy]
  end

  resources :comments do
    get 'all', on: :member
    post 'ban', on: :member
  end

  resources :users, only: [:show,:edit,:update,:destroy] do
    post 'set_payment_password', on: :member
    patch 'update_payment_password', on: :member
  end

  resources :carts, only: [:show,:destroy] do
    get 'add_item', on: :collection
  end

  resources :items, only: [:destroy]

  resources :orders, only: [:index,:show,:create] do
    member do
      post 'preview'
      get 'payment'
      post 'paid'
      patch 'confirm'
    end
  end

  resources :marks, only: [:index, :create, :destroy] do
    delete 'remove', on: :member
  end

  resources :categories, only: [:show]

  resources :awards, only: [:index] do
    get 'show_all', on: :collection
    get 'judge', on: :collection
  end

  resources :coupons, only: [:index]

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :products, through: :items
  accepts_nested_attributes_for :items

  attr_accessor :verify_code
  validates :buyer, presence: true, length: {minimum: 2, maximum: 20}
  validates :phone, presence: true, length: {minimum: 5, maximum: 15}
  validates :address, presence: true, length: {maximum: 60}
  validates :user_id, presence: true
  
  before_create :calculate_item_total
  before_create :calculate_order_total
  before_create :check_coupon
  before_create :set_default_status

  after_create :handle_job  #not for heroku

  def handle_job
    OrderHandlerJob.set(wait: 1.weeks).perform_later(self)
  end

  def build_items(selected_items)
    selected_items.each do |i|
      if i[:product_id]
         self.items.build(product_id: i[:product_id],
                         quantity: i[:quantity],
                         product_type: i[:product_type])
    
      end
    end
  end

  def not_paid?
    self.status == "not_paid"
  end

  def pay_by(user)
    user.update_attributes(money: user.money - self.total)
    self.update_attributes(status: "paid")

    increment_sales_counter
    update_inventory
    delete_cart_items
  end

  def update_user_score
     user = self.user
     user.update_attributes(score: user.score + self.total) 
  end

  private

  def calculate_item_total  #计算各个item的合计价
    self.items.each do |item|
      product = Product.find(item.product_id)
      item.total = item.quantity * product.price
    end
  end

  def calculate_order_total  #计算订单总价
    self.total = 0
    self.items.map {|i| self.total += i.total}
  end


  def check_coupon
    if !self.verify_code.blank?
      coupon = Coupon.find_by_verify_code(self.verify_code)
      if coupon && coupon.expire_at > Time.now
        if self.total - coupon.value < 0
          self.total == 0
        else
          self.total -= coupon.value
        end
        coupon.delete
      end
    end
  end


  def set_default_status
     self.status = "not_paid"
  end


  def increment_sales_counter
    self.items.map { |i| i.product.update_attributes(sales: i.product.sales + i.quantity) }
  end


  def update_inventory  #更新库存
    self.items.each do |i|
      p = i.product
      p.update_attributes(inventory: p.inventory - i.quantity)
    end
  end


  def delete_cart_items
    cart_items = user.cart.items
    self.items.each do |i|
      type = i.product_type.blank? ? nil : i.product_type
      cart_items.where(product_id: i.product_id,product_type: type).destroy_all
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  after_action :set_status_job, only: :deliver

  def index
    @paid_orders = Order.where(status: "paid").includes(:products)
    @sent_orders = Order.where(status: "sent").includes(:products)
    @history_orders = Order.where(status: "confirm").includes(:products)

    @statistic_orders = Order.where("status = ? OR status = ?","paid","confirm").includes(:products)
    today_orders = @statistic_orders.where("created_at > ?", Time.now.midnight)
    @today_sales = sales_amount(today_orders)

    week_orders = @statistic_orders.where("created_at > ?", (Time.now.wday).days.ago.midnight)
    @week_sales = sales_amount(week_orders)

    month_orders = @statistic_orders.where("created_at > ?", (Time.now.mday - 1).days.ago.midnight)
    @month_sales = sales_amount(month_orders)

    year_orders = @statistic_orders.where("created_at > ?", (Time.now.yday - 1).days.ago.midnight)
    @year_sales = sales_amount(year_orders)
  end

  def show_products
    @order = Order.find(params[:id])
    render "orders/show_products"  
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update_attributes(order_params)
    flash[:notice] = "修改完成"
    redirect_to admin_orders_path
  end

  def deliver
    @order = Order.find(params[:id])
    if @order.update_attributes(status: "sent")
      respond_to do |format|
       format.js
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.delete
    redirect_to admin_orders_path
  end

  private
  def order_params
    params.require(:order).permit(:buyer, :phone,:address)
  end

  def sales_amount(orders)
    total = 0
    orders.each do |order|
      total += order.total
    end
    return total
  end

  def set_status_job
    @order.handle_job
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!
  before_action :check_type,only: :preview
  before_action :check_quantity, only: :preview
  before_action :insure_not_paid, only: [:payment,:paid]
  before_action :authenticate_password, only: :paid
  before_action :insure_enough_money, only: :paid

  after_action :update_score, only: :confirm
  load_and_authorize_resource except: :preview

  def index
    @orders = current_user.orders.includes(:products,:items).paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def preview
    if params[:commit] == "加入购物车"
      redirect_to add_item_carts_path(items: params[:items])
    end
    @order = current_user.orders.build
    @order.build_items(params[:items])
  end

  def create
    @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to payment_order_path(@order)
    else
      flash[:notice] = "提交订单失败"
      render 'preview'
    end
  end

  def payment
  end

  def paid
    @order.pay_by(current_user)
    redirect_to orders_path
  end

  def confirm
    @order = Order.find(params[:id])
    @order.update_attributes(status: "confirm")
    respond_to do |format|
      format.js
    end
  end

  private
  def order_params
    params.require(:order).permit(:buyer,:phone,:address,:user_id,:verify_code,
                                  items_attributes: [:product_id,:quantity,:product_type]
                                  )
  end

  def check_type
    params[:items].each do |item|
      if item[:product_type].blank?
        @product = Product.find(item[:product_id])
        if @product.type_list.any?
          flash[:notice] = "你未指定类型"
          redirect_to @product
        end
      end
    end
  end

  def check_quantity
    params[:items].each do |item|
      if item[:quantity].to_i <= 0
        flash[:notice] = "数量不能少于1"
        redirect_to(:back)
      end
    end
  end

  def insure_not_paid
    @order = current_user.orders.find(params[:id])
    unless @order.not_paid?
      flash[:notice] = "该订单已完成或关闭"
      redirect_to orders_path
    end
  end
  
  def authenticate_password
    unless current_user.confirm_payment_password(params[:payment_password])
      flash[:alert] = "支付密码错误"
      render 'payment'
    end
  end

  def insure_enough_money
    unless current_user.money >= @order.total
      flash[:alert] = "账号余额不足！"
      render 'payment'
    end
  end

  def update_score
     @order.update_user_score
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/views/admin/orders/deliver.js.erb
$(".order_<%= @order.id%>").remove();
alert("成功标记为发货");

app/views/admin/orders/destroy.html.erb
<h1>Admin::Orders#destroy</h1>
<p>Find me in app/views/admin/orders/destroy.html.erb</p>

app/views/admin/orders/edit.html.erb
<h1>修改订单信息</h1>
	<%= simple_form_for [:admin, @order] do |f|%>
	<%= f.input :buyer%>
	<%= f.input :phone%>
	<%= f.input :address%>
	<%= f.submit '提交', class: "btn btn-lg btn-info"%>
<%end%>

app/views/admin/orders/index.html.erb
<div class="col-md-10 col-md-offset-1">

   <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#paid" aria-controls="paid" role="tab" data-toggle="tab">待发货</a></li>
            <li role="presentation"><a href="#sent" aria-controls="sent" role="tab" data-toggle="tab"> 已发货</a></li>
            <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">已完成交易</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="paid">
                
                <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">待发货订单</h3>
        </div>
        <div class="panel-body">

            <table class="table table-hover datatable">
                <thead>
                    <tr>
                        <th><b>订单编号</b></th>
                        <th><b>买家</b></th>
                        <th><b>联系电话</b></th>
                        <th><b>地址</b></th>
                        <th><b>商品</b></th>
                        <th><b>总价</b></th>
                        <th><b>时间</b></th>
                        <th><b>操作</b></th>
                    </tr>
                </thead>
                <tbody>
                    <% @paid_orders.each do |order|%>
                        <tr>
                            <td>
                                <%= link_to order.id, edit_admin_order_path(order)%>
                            </td>
                            <td>
                                <%= order.buyer%>
                            </td>
                            <td>
                                <%= order.phone%>
                            </td>
                            <td>
                                <%= order.address%>
                            </td>
                            <td>
                                <%= link_to "查看",show_products_admin_order_path(order)%>
                            </td>
                            <td>
                                <%= order.total%>
                            </td>
                            <td>
                                <%= order.created_at.to_s(:db)%>
                            </td>
                            <td>
                                <%= link_to '发货',deliver_admin_order_path(order),method: :post,remote: true,class: "order_#{order.id}"%>
                                <%= link_to '编辑', edit_admin_order_path(order)%>,
                                    <%= link_to '删除', admin_order_path(order), method: :delete%>
                            </td>
                        </tr>
                        <%end%>
                </tbody>
            </table>
        </div>
    </div>

            </div>

            <div role="tabpanel" class="tab-pane" id="sent">
                <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">已发货订单</h3>
        </div>
        <div class="panel-body">
          <table class="table table-hover datatable">
                <thead>
                    <tr>
                        <th><b>订单编号</b></th>
                        <th><b>买家</b></th>
                        <th><b>联系电话</b></th>
                        <th><b>地址</b></th>
                        <th><b>商品</b></th>
                        <th><b>总价</b></th>
                        <th><b>时间</b></th>
                        <th><b>操作</b></th>
                    </tr>
                </thead>
                <tbody>
                    <% @sent_orders.each do |order|%>
                        <tr>
                            <td>
                                <%= link_to order.id, edit_admin_order_path(order)%>
                            </td>
                            <td>
                                <%= order.buyer%>
                            </td>
                            <td>
                                <%= order.phone%>
                            </td>
                            <td>
                                <%= order.address%>
                            </td>
                            <td>
                                <%= link_to "查看",show_products_admin_order_path(order)%>
                            </td>
                            <td>
                                <%= order.total%>
                            </td>
                            <td>
                                <%= order.created_at.to_s(:db)%>
                            </td>
                            <td>
                                <%= link_to '编辑', edit_admin_order_path(order)%>,
                                    <%= link_to '删除', admin_order_path(order), method: :delete%>
                            </td>
                        </tr>
                        <%end%>
                </tbody>
            </table>
        </div>
    </div>

            </div>

            <div role="tabpanel" class="tab-pane" id="history">

              <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">历史订单</h3>
        </div>
        <div class="panel-body">
          <table class="table table-hover datatable">
                <thead>
                    <tr>
                        <th><b>订单编号</b></th>
                        <th><b>买家</b></th>
                        <th><b>联系电话</b></th>
                        <th><b>地址</b></th>
                        <th><b>商品</b></th>
                        <th><b>总价</b></th>
                        <th><b>时间</b></th>
                        <th><b>操作</b></th>
                    </tr>
                </thead>
                <tbody>
                    <% @history_orders.each do |order|%>
                        <tr>
                            <td>
                                <%= link_to order.id, edit_admin_order_path(order)%>
                            </td>
                            <td>
                                <%= order.buyer%>
                            </td>
                            <td>
                                <%= order.phone%>
                            </td>
                            <td>
                                <%= order.address%>
                            </td>
                            <td>
                                <%= link_to "查看",show_products_admin_order_path(order)%>
                            </td>
                            <td>
                                <%= order.total%>
                            </td>
                            <td>
                                <%= order.created_at.to_s(:db)%>
                            </td>
                            <td>
                            
                                    <%= link_to '删除', admin_order_path(order), method: :delete%>
                            </td>
                        </tr>
                        <%end%>
                </tbody>
            </table>
        </div>
    </div>
            </div>
        </div>

     



    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">统计信息</h3>
        </div>
        <div class="panel-body">

            <div class="normal_border">
        <div>今日销售额：
            <%= @today_sales%>
        </div>
        <div>本周销售额：
            <%= @week_sales%>
        </div>
        <div>本月销售额：
            <%= @month_sales%>
        </div>
        <div>年度销售额：
            <%= @year_sales%>
        </div>
    </div>

        </div>
    </div>
    

</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>