config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",registrations: "users/registrations"}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  root 'products#index'

  get '/search', to: 'products#search'
  get '/auto_search', to: 'products#auto_search'

  mount RuCaptcha::Engine => "/rucaptcha"

  namespace :admin do
    root 'home#dashboard'
    get '/root_manage', to: 'home#root_manage'

    resources :banners,only: [:create,:update,:destroy]

    resources :categories

    resources :products, except: [:show]

    resources :images, only: [:create] do
      delete 'del_image', on: :collection
    end

    resources :users, only: [:index, :edit, :update, :destroy] do
      post 'add', on: :collection
      delete 'remove', on: :member
    end

    resources :orders, only: [:index, :edit, :update, :destroy] do
      get "show_products", on: :member
      post 'deliver', on: :member
    end

    resources :coupons, only: [:index,:create]

    resources :awards, only: [:index,:create,:edit,:update,:destroy]
  end

  resources :products do
    get 'detail', on: :member
    resources :comments, only: [:index,:create, :destroy]
  end

  resources :comments do
    get 'all', on: :member
    post 'ban', on: :member
  end

  resources :users, only: [:show,:edit,:update,:destroy] do
    post 'set_payment_password', on: :member
    patch 'update_payment_password', on: :member
  end

  resources :carts, only: [:show,:destroy] do
    get 'add_item', on: :collection
  end

  resources :items, only: [:destroy]

  resources :orders, only: [:index,:show,:create] do
    member do
      post 'preview'
      get 'payment'
      post 'paid'
      patch 'confirm'
    end
  end

  resources :marks, only: [:index, :create, :destroy] do
    delete 'remove', on: :member
  end

  resources :categories, only: [:show]

  resources :awards, only: [:index] do
    get 'show_all', on: :collection
    get 'judge', on: :collection
  end

  resources :coupons, only: [:index]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :user_id,presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  def show
    @items = current_user.cart.items.includes(:product).paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def add_item
    item_params = params[:items][0]
    @item = current_user.cart.items.build(product_id: item_params[:product_id],
      quantity: item_params[:quantity],product_type: item_params[:product_type])
    respond_to do |format|
      if @item.save
        format.html {redirect_to @item.product,notice: "成功加入购物车"}
      else
        format.html{redirect_to @item.product,alert: "未指定商品种类！"}
      end
    end
  end

  def destroy
    @items = current_user.cart.items.all
    @items.delete_all
    redirect_to cart_path(current_user.cart)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="col-md-8 col-md-offset-2">
    <%if @items.blank?%>
        <h3 class="notify">您的购物车空空如也～</h3>
        <%else%>
            <h2 class="inline">购物车共有<%=@items.count%>件商品</h2>
            <%= link_to '清空购物车', cart_path(current_user.cart), method: :delete,class: "btn btn-info pull-right",data: {confirm: "确定要清空购物车内#{@items.count}件商品?"}%>
                <hr>
                <div class="col-md-1">
                </div>
                <div class="col-md-4">
                    <strong>商品信息</strong>
                </div>
                <div class="col-md-2">
                    <strong>单价(元)</strong>
                </div>
                <div class="col-md-2">
                    <strong>数量</strong>
                </div>
                <div class="col-md-2">
                    <strong>操作</strong>
                </div>
                <br>
                <%= form_tag preview_order_path do %>
                    <% @items.each do |item|%>
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                创建时间：
                                <%= format_time(item.created_at)%>
                            </div>
                            <div class="panel-body">
                                <div class="col-md-1">
                                    <%= check_box_tag 'items[][product_id]', item.product_id%>
                                </div>
                                <div class="col-md-2">
                                    <%=link_to image_tag(item.product.picture,size:"80x80"),product_path(item.product)%>
                                </div>
                                <div class="col-md-2">
                                    <%=link_to item.product.name, product_path(item.product)%>
                                    <% if item.product_type %>
                                            <div>
                                                <small class="explanation">颜色／分类：<strong><%= item.product_type%></strong></small>
                                            </div>
                                             <%= hidden_field_tag 'items[][product_type]',item.product_type %>
                                            <%end%>
                                </div>
                                <div class="col-md-2">
                                    <%= item.product.price%>
                                </div>
                                <div class="col-md-2">
                                    <%= text_field_tag 'items[][quantity]', item.quantity,size: "1x1"%>
                                </div>
                                <div class="col-md-2">
                                 
                                        <%= link_to '删除', item_path(item),method: :delete%>
                                </div>
                            </div>
                        </div>
                        <%end%>
                            <%= submit_tag '结算',class: "pull-right btn btn-lg btn-secondary"%>
                                <%end%>
                                    <!--form_tag-->
                                    <%= will_paginate @items%>
                                        <%end%>
</div>