config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",registrations: "users/registrations"}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  root 'products#index'

  get '/search', to: 'products#search'
  get '/auto_search', to: 'products#auto_search'

  mount RuCaptcha::Engine => "/rucaptcha"

  namespace :admin do
    root 'home#dashboard'
    get '/root_manage', to: 'home#root_manage'

    resources :banners,only: [:create,:update,:destroy]

    resources :categories

    resources :products, except: [:show]

    resources :images, only: [:create] do
      delete 'del_image', on: :collection
    end

    resources :users, only: [:index, :edit, :update, :destroy] do
      post 'add', on: :collection
      delete 'remove', on: :member
    end

    resources :orders, only: [:index, :edit, :update, :destroy] do
      get "show_products", on: :member
      post 'deliver', on: :member
    end

    resources :coupons, only: [:index,:create]

    resources :awards, only: [:index,:create,:edit,:update,:destroy]
  end

  resources :products do
    get 'detail', on: :member
    resources :comments, only: [:index,:create, :destroy]
  end

  resources :comments do
    get 'all', on: :member
    post 'ban', on: :member
  end

  resources :users, only: [:show,:edit,:update,:destroy] do
    post 'set_payment_password', on: :member
    patch 'update_payment_password', on: :member
  end

  resources :carts, only: [:show,:destroy] do
    get 'add_item', on: :collection
  end

  resources :items, only: [:destroy]

  resources :orders, only: [:index,:show,:create] do
    member do
      post 'preview'
      get 'payment'
      post 'paid'
      patch 'confirm'
    end
  end

  resources :marks, only: [:index, :create, :destroy] do
    delete 'remove', on: :member
  end

  resources :categories, only: [:show]

  resources :awards, only: [:index] do
    get 'show_all', on: :collection
    get 'judge', on: :collection
  end

  resources :coupons, only: [:index]

end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base
  acts_as_taggable_on :types

  has_many :items, dependent: :destroy
  has_many :orders, through: :items, dependent: :destroy
  belongs_to :category
  has_many :marks, dependent: :destroy
  has_many :marking_users, through: :marks, source: :user
  has_many :preview_images, as: :imageable,class_name: "Image", dependent: :destroy
  has_many :comments, as: :commentable,dependent: :destroy
  mount_uploader :picture, PictureUploader


  validates :name, presence: true, length: {maximum: 50},uniqueness: {case_sensitive: false}
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :inventory, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  before_save :handle_type_list
  after_save :add_to_suggestions  #not for heroku

  before_update :remove_suggestions #not for heroku
 

  def handle_type_list
   self.type_list = type_list[0].to_s.gsub(/ /,",")
  end
  
  def add_to_suggestions
     AutoSearch.add_product_term(self.id)
  end

  def remove_suggestions
    AutoSearch.remove_product_term(self.id)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :destroy_suggestions, only: :destroy  #not for heroku
  def index
    @products = Product.all#.paginate(page: params[:page], per_page: 30).order("created_at desc")
  end

  def new
    @product = Product.new
    @selectable_categories = Category.where.not(ancestry: 0)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "创建成功"
    else
      flash[:notice] = "出错啦！"
    end
    redirect_to admin_products_path
  end

  def edit
    @product = Product.find(params[:id])
    @selectable_categories = Category.where.not(ancestry: 0)
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "update successful"
    else
      flash[:notice] = "failed!"
    end
    redirect_to admin_products_path
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.delete
      flash[:notice] = "删除成功"
    else
      flash[:notice] = "出错啦！"
    end
    redirect_to admin_products_path
  end


  private
  def product_params
    params.require(:product).permit(:name,:price,:inventory,:picture,
                                    :introduction, :category_id,{type_list: []}) 
  end
  
  def destroy_suggestions
    @product.remove_suggestions
  end
end

app/controllers/products_controller.rb
# -*- encoding : utf-8 -*-
class ProductsController < ApplicationController

  load_and_authorize_resource
  def index
    @products = Product.all.order("created_at desc")
    @hot_sales = Product.where.not(sales: 0).order("sales desc").limit(10)
    @banners = Banner.all.order("created_at DESC")
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.order("created_at DESC").limit(10)
  end


  def search
    @products = Product.where("name LIKE ?", params[:query])
  end

  def auto_search
    render json: AutoSearch.terms_for(params[:term])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
# -*- encoding : utf-8 -*-
module ProductsHelper
end

app/views/admin/products/_product_form.html.erb
<%= simple_form_for [:admin,@product] do |f|%>
	<%= f.input :name, label: "商品名"%>
	<%= f.input :price, label: "零售价"%>
	<%= f.input :inventory, label: "库存"%>
	<%= f.association :category, collection: @selectable_categories, label: "商品分类"%>
	<%= f.input :type_list,input_html: {multiple: 'multiple'},label: "商品规格／大小／类型(空格键分隔)"%>
	<%= f.input :picture, label: "展示图"%>
	<%= f.input :introduction, label: "商品描述"%>
	<%= f.submit "确认", class: "btn-lg btn-success"%>
<%end%>

app/views/admin/products/create.html.erb
<h1>Admin::Products#create</h1>
<p>Find me in app/views/admin/products/create.html.erb</p>

app/views/admin/products/destroy.html.erb
<h1>Admin::Products#destroy</h1>
<p>Find me in app/views/admin/products/destroy.html.erb</p>

app/views/admin/products/edit.html.erb
<div role="tabpanel" class="tab-pane" id="photo">
     
     
     <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#multi" aria-controls="multi" role="tab" data-toggle="tab">多图上传</a></li>
    <li role="presentation"><a href="#single" aria-controls="single" role="tab" data-toggle="tab">单图上传</a></li>
    <li role="presentation"><a href="#show_images" aria-controls="show_images" role="tab" data-toggle="tab">查看预览图</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="multi">
     <div id="dropzone" class="fade">把选好的图片拖拽到这即可自动上传</div>
     
    <%= simple_form_for [:admin,@product.preview_images.build] do |f|%>
        <%= f.input :imageable_id,as: :hidden,input_html: {value: @product.id}%>
            <%= f.input :url,as: :file,label: false,input_html: {multiple: true,name: 'image[url]'}%>
               
        <div class="progress-wrapper">
          <p>Bitrate: <span class="bitrate"></span></p>
         <div class="progress">
          <div class="progress-bar" role="progressbar">
           0%
          </div>
         </div>
         </div>
      <%end%>

    </div>

    <div role="tabpanel" class="tab-pane" id="single">
      <%= simple_form_for [:admin,@product.preview_images.build],remote: true do |f| %>
       <%= f.input :url,as: :file,label: "单张图片上传"%>
       <%= f.submit "上传"%>
      <%end%>
    </div>
    
    <div role="tabpanel" class="tab-pane" id="show_images">
       <div id="images-list">
        <div class="row">
        <%= render @product.preview_images%>
        </div>
       </div>

    </div>
   </div>


<div class="normal_border">
    <%= render 'product_form'%>
</div>

<script>
  $(document).ready(function() {
    var multiple_photos_form = $('#new_image');
    multiple_photos_form.fileupload({dataType: 'script'});
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var progress_bar = wrapper.find('.progress-bar');


   multiple_photos_form.fileupload({
   dataType: 'script',
   dropZone: $('#dropzone'),
   add: function (e, data) {
    types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
    file = data.files[0];
    if (types.test(file.type) || types.test(file.name)) {
      data.submit();
    }
    else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
  }
  });


multiple_photos_form.on('fileuploadstart', function() {
  wrapper.show();
});

multiple_photos_form.on('fileuploaddone', function() {
  wrapper.hide();
  progress_bar.width(0); // Revert progress bar's width back to 0 for future uploads
});

multiple_photos_form.on('fileuploadprogressall', function (e, data) {
  var progress = parseInt(data.loaded / data.total * 100, 10);
  progress_bar.css('width', progress + '%').text(progress + '%');
});



  var bitrate = wrapper.find('.bitrate');

multiple_photos_form.on('fileuploadprogressall', function (e, data) {
  bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');

  var progress = parseInt(data.loaded / data.total * 100, 10);
  progress_bar.css('width', progress + '%').text(progress + '%');
});


  $(document).bind('dragover', function (e) {
  var dropZone = $('#dropzone'),
          timeout = window.dropZoneTimeout;
  if (!timeout) {
    dropZone.addClass('in');
  } else {
    clearTimeout(timeout);
  }
  var found = false,
          node = e.target;
  do {
    if (node === dropZone[0]) {
      found = true;
      break;
    }
    node = node.parentNode;
  } while (node != null);
  if (found) {
    dropZone.addClass('hover');
  } else {
    dropZone.removeClass('hover');
  }
  window.dropZoneTimeout = setTimeout(function () {
    window.dropZoneTimeout = null;
    dropZone.removeClass('in hover');
  }, 100);
});
  });
 

</script>

app/views/admin/products/index.html.erb
<div class="col-md-10 col-md-offset-1">
    <div class="panel panel-info">
        <div class="panel-heading"> 商品表
            <%= link_to "新建商品", new_admin_product_path,class: "pull-right btn btn-sm btn-success"%>
        </div>
        <div class="panel-body">
            <table class="datatable table table-hover">
                <thead class="table-info">
                    <tr>
                        <th><b>id</b></th>
                        <th><b>商品名</b></th>
                        <th><b>零售价</b></th>
                        <th><b>库存</b></th>
                        <th><b>操作</b></th>
                    </tr>
                </thead>
                <tbody>
                    <% @products.each do |product|%>
                        <tr>
                            <td>
                                <%= link_to product.id, edit_admin_product_path(product), 'data-no-turbolink' => true%>
                            </td>
                            <td>
                                <%= link_to product.name, edit_admin_product_path(product),'data-no-turbolink' => true%>
                            </td>
                            <td>
                                <%= product.price%>
                            </td>
                            <td>
                                <%= product.inventory%>
                            </td>
                            <td>
                                <%= link_to '删除', admin_product_path(product), method: :delete%>
                            </td>
                        </tr>
                        <%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/admin/products/new.html.erb
<div class="normal_border">
<%= render 'product_form'%>
</div>

app/views/admin/products/update.html.erb
<h1>Admin::Products#update</h1>
<p>Find me in app/views/admin/products/update.html.erb</p>