config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",registrations: "users/registrations"}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  root 'products#index'

  get '/search', to: 'products#search'
  get '/auto_search', to: 'products#auto_search'

  mount RuCaptcha::Engine => "/rucaptcha"

  namespace :admin do
    root 'home#dashboard'
    get '/root_manage', to: 'home#root_manage'

    resources :banners,only: [:create,:update,:destroy]

    resources :categories

    resources :products, except: [:show]

    resources :images, only: [:create] do
      delete 'del_image', on: :collection
    end

    resources :users, only: [:index, :edit, :update, :destroy] do
      post 'add', on: :collection
      delete 'remove', on: :member
    end

    resources :orders, only: [:index, :edit, :update, :destroy] do
      get "show_products", on: :member
      post 'deliver', on: :member
    end

    resources :coupons, only: [:index,:create]

    resources :awards, only: [:index,:create,:edit,:update,:destroy]
  end

  resources :products do
    get 'detail', on: :member
    resources :comments, only: [:index,:create, :destroy]
  end

  resources :comments do
    get 'all', on: :member
    post 'ban', on: :member
  end

  resources :users, only: [:show,:edit,:update,:destroy] do
    post 'set_payment_password', on: :member
    patch 'update_payment_password', on: :member
  end

  resources :carts, only: [:show,:destroy] do
    get 'add_item', on: :collection
  end

  resources :items, only: [:destroy]

  resources :orders, only: [:index,:show,:create] do
    member do
      post 'preview'
      get 'payment'
      post 'paid'
      patch 'confirm'
    end
  end

  resources :marks, only: [:index, :create, :destroy] do
    delete 'remove', on: :member
  end

  resources :categories, only: [:show]

  resources :awards, only: [:index] do
    get 'show_all', on: :collection
    get 'judge', on: :collection
  end

  resources :coupons, only: [:index]

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  include BCrypt
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :old_payment_password,:payment_password_handler

  has_one :cart, dependent: :destroy
  has_many :orders
  has_many :marks, dependent: :destroy
  has_many :mark_products, through: :marks, source: :product
  has_many :comments
  has_many :authorities, dependent: :destroy
  has_many :roles, through: :authorities
  has_many :coupons, dependent: :destroy
  has_many :award_items, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:github,:twitter,:facebook]

  validates :nick_name, presence: true, length: {minimum: 2, maximum: 15},
    uniqueness: {case_sensitive: false}

  validates :payment_password_handler,length: {is: 6},
    numericality: {only_integer: true},confirmation: true,:if => :payment_password_exist?
  validates :payment_password_handler_confirmation,presence: true, :if => :payment_password_exist?

  before_save :bcrypt_payment_password
  before_create :set_test_money
  after_create :create_cart


  def payment_password_exist?
    !payment_password_handler.nil?
  end

  def bcrypt_payment_password
    if self.payment_password_handler
       self.payment_password = Password.create(self.payment_password_handler)
    end
  end

  def set_test_money
    self.money = 1000
  end

  def create_cart
    Cart.create(user_id: self.id)
  end


  def confirm_payment_password(password)
    Password.new(payment_password) == password
  end
 
 
  def check_avatar
    if avatar.blank?
      "default_avatar.jpg"
    else
      avatar
    end
  end

  def has_role?(role)
    if roles.find_by_name(role)
      true
    else
      false
    end
  end


  def ban_comment(ban_time)
    update_attributes(ban_comment_until: (Time.now + ban_time))
  end

  Super_admin = ["admin@admin.com"]
  def super_admin?
    Super_admin.include?(email)
  end

  def marking?(product)
    marks.find_by_product_id(product)
  end

  def unmarked!(mark_product)
    marks.find_by_product_id(mark_product).destroy
  end


  def self.from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.nick_name = auth_hash['info']['name']
    user.email = auth_hash['info']['email'] || "#{user.uid}@sshop.com"
    user.password = Devise.friendly_token[0,12]
    #user.location = auth_hash['info']['location']
    user.remote_avatar_url = auth_hash['info']['image']
    user.save!
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      elsif data = session["devise.twitter_data"] && session["devise.twitter_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      elsif data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :insure_super_admin, only: [:add, :remove]

  def index
    @users = User.all
    @admin_users = Role.find_by_name("admin").users
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "update successful"
    else
      flash[:notice] = "failed!"
    end
    redirect_to admin_users_path
  end

  def add
    @user = User.find_by_email(params[:email])
    if @user.authorities.create!(role_id: 1)
      flash[:notice] = "添加成功"
    else
      flash[:notice] = "出现错误！"
    end
    redirect_to admin_users_path
  end

  def remove
    @user = User.find(params[:id])
    @user.authorities.find_by_role_id(1).delete unless @user.super_admin?
    redirect_to admin_users_path
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:nick_name,:real_name, :phone, :address)
  end

  def insure_super_admin
    redirect_to admin_users_path unless current_user.super_admin?
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  before_filter :verify_rucaptcha, only: :create
  # GET /resource/sign_up
   #def new
     #super
   #end

  # POST /resource
   #def create
    #super
   #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected
   
  def verify_rucaptcha
   unless verify_rucaptcha?(resource)
      flash[:notice] = "验证码错误"
      redirect_to new_user_registration_path      
   end
  end

  

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  include BCrypt

  before_action :authenticate_user!
  before_action :authenticate_old_payment_password, only: :update_payment_password
  load_and_authorize_resource

  def show
  end

  def edit
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "完成更新"
      redirect_to root_path
    else
      flash[:alert] = "更新失败"
      render 'edit'
    end
  end

  def set_payment_password
    if current_user.update_attributes(payment_params)
      flash[:notice] = "更新成功"
      redirect_to edit_user_path(current_user)
    else
      flash[:notice] = "密码不符合要求"
      render 'edit'
    end

  end

  def update_payment_password

    if current_user.update_attributes(payment_params)
      flash[:notice] = "更新成功"
      redirect_to edit_user_path(current_user)
    else
      flash[:notice] = "密码不符合要求"
      render 'edit'
    end
  end

  def destroy
  end


  private
  def user_params
    params.require(:user).permit(:avatar,:real_name,:phone,:address,
                                 :sex,:age,:s_province,:s_city,:s_county)
  end

  def payment_params
    params.require(:user).permit(:old_payment_password,:payment_password_handler,:payment_password_handler_confirmation)
  end

  def authenticate_old_payment_password
    unless current_user.confirm_payment_password(params[:user][:old_payment_password])
      flash[:notice] = "旧支付密码错误"
      render 'edit'
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<%= simple_form_for [:admin,@user] do |f|%>
	<%= f.input :nick_name%>
	<%= f.input :real_name%>
	<%= f.input :phone%>
	<%= f.input :address%>
	<%= f.submit "submit"%>
<%end%>

app/views/admin/users/index.html.erb
<div class="col-md-8 col-md-offset-2">

  <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#common" aria-controls="common" role="tab" data-toggle="tab">普通用户</a></li>
            <li role="presentation"><a href="#admin" aria-controls="admin" role="tab" data-toggle="tab">管理员</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="common">
                <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">用户管理</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover datatable">
                <thead>
                    <tr>
                        <th><b>id</b></th>
                        <th><b>email</b></th>
                        <th><b>昵称</b></th>
                        <th><b>联系电话</b></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user|%>
                        <tr>
                            <td>
                                <%= link_to user.id, edit_admin_user_path(user)%>
                            </td>
                            <td>
                                <%= link_to user.email, edit_admin_user_path(user)%>
                            </td>
                            <td>
                                <%= user.nick_name%>
                            </td>
                            <td>
                                <%= user.phone%>
                            </td>
                        </tr>
                        <%end%>
                </tbody>
            </table>
        </div>
        <!--panel-body-->
    </div>
    <!--panel-->

            </div>
            <div role="tabpanel" class="tab-pane" id="admin">
                <div class="panel panel-warning">
        <div class="panel-heading">
            <div class="panel-title">管理员管理</div>
        </div>
        <div class="panel-body">
            <%if current_user.super_admin?%>
                <div class="form-inline pull-right">
                    <%= form_tag add_admin_users_path do %>
                    <%= text_field_tag :email, params[:email],class: "form-control ",placeholder: "输入要添加的email帐号"%>
                    <%= submit_tag '添加管理员', class: "btn btn-primary"%>
                    <%end%>
                </div>
                <%end%>

                    <table class="table table-hover datatable">
                        <thead>
                            <tr>
                                <th><b>id</b></th>
                                <th><b>email</b></th>
                                <th><b>昵称</b></th>
                                <th><b>联系电话</b></th>
                                <th><b>操作</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @admin_users.each do |user|%>
                                <tr>
                                    <td>
                                        <%= link_to user.id, edit_admin_user_path(user)%>
                                    </td>
                                    <td>
                                        <%= link_to user.email, edit_admin_user_path(user)%>
                                    </td>
                                    <td>
                                        <%= user.nick_name%>
                                    </td>
                                    <td>
                                        <%= user.phone%>
                                    </td>
                                    <td>
                                        <% if current_user.super_admin?%>
                                        <%= link_to '移除', remove_admin_user_path(user), method: :delete unless user == current_user%>
                                         <%end%>
                                    </td>
                                </tr>
                            <%end%>
                        </tbody>
                    </table>
        </div>
        <!--panel-body-->
    </div>
    <!--panel -->

            </div>
        </div>



    
</div>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>